import React from 'react';
import { IconSparkles } from '../../assets/icons/Icons';

interface AiSuggestionBannerProps {
  label?: string;
  subtext?: string;
  children: React.ReactNode;
  onAccept?: () => void;
  onEdit?: () => void;
  isEditable?: boolean;
}

export const AiSuggestionBanner: React.FC<AiSuggestionBannerProps> = ({
  label = 'Suggested — please review',
  subtext = 'Generated by AI assistant. Human confirmation is required before proceeding.',
  children,
  onAccept,
  onEdit,
  isEditable = true,
}) => {
  return (
    <div className="ai-suggestion-box">
      <div className="ai-suggestion-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <span className="ai-tag">
            <IconSparkles size={14} />
            <span>{label}</span>
          </span>
        </div>
        {subtext && (
          <span style={{ fontSize: '0.78rem', color: 'var(--color-neutral-500)' }}>
            {subtext}
          </span>
        )}
      </div>

      <div style={{ margin: '10px 0' }}>
        {children}
      </div>

      {(onAccept || onEdit) && (
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px', marginTop: '10px' }}>
          {onEdit && (
            <button type="button" onClick={onEdit} className="btn btn-secondary btn-sm">
              Edit Draft
            </button>
          )}
          {onAccept && (
            <button type="button" onClick={onAccept} className="btn btn-primary btn-sm">
              Accept Suggestion
            </button>
          )}
        </div>
      )}
    </div>
  );
};
